/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Directorio;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
/**
 *
 * @author H
 */
public class VBuscarCliente extends javax.swing.JInternalFrame {
DefaultListModel listaClientes = new DefaultListModel();
    /**
     * Creates new form VBuscarCliente
     */
    public VBuscarCliente() {
       
        
        initComponents();
        jList1.setModel(listaClientes);
        listaClientes.removeAllElements();
        jList1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTFbuscarPor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTEncontradonombre = new javax.swing.JTextField();
        jBborrar = new javax.swing.JButton();
        jTencontradoApellido = new javax.swing.JTextField();
        jTencontradoDni = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        etiqueta_lista_mostrando = new javax.swing.JLabel();
        jTencontradoDireccion = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Buscar Cliente");

        jLabel1.setText("BUSCAR CLIENTE POR:");

        jTFbuscarPor.setText("ingrese telefono");
        jTFbuscarPor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFbuscarPorFocusGained(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTEncontradonombre.setEditable(false);
        jTEncontradonombre.setText("nombre");
        jTEncontradonombre.setFocusable(false);

        jBborrar.setText("Borrar Cliente");
        jBborrar.setEnabled(false);
        jBborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBborrarActionPerformed(evt);
            }
        });

        jTencontradoApellido.setEditable(false);
        jTencontradoApellido.setText("apellido");
        jTencontradoApellido.setFocusable(false);

        jTencontradoDni.setEditable(false);
        jTencontradoDni.setText("dni");
        jTencontradoDni.setFocusable(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Telefono", "Apellido", "Ciudad" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jTencontradoDireccion.setText("direccion");
        jTencontradoDireccion.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTFbuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addContainerGap(92, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBborrar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(jTEncontradonombre)
                            .addComponent(jTencontradoApellido)
                            .addComponent(jTencontradoDni)
                            .addComponent(jScrollPane1)
                            .addComponent(etiqueta_lista_mostrando, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTencontradoDireccion))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFbuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTEncontradonombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTencontradoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTencontradoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTencontradoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBborrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(etiqueta_lista_mostrando, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
      
        
        switch(jComboBox1.getSelectedIndex()){
            case 0:
                
                listaClientes.removeAllElements();
                
                if(jTFbuscarPor.getText().equals("")){
                JOptionPane.showConfirmDialog(this, "SIN NUMERO A BUSCAR");
                
                }
                
                if(!Directorio.buscarCliente(jTFbuscarPor.getText()).getNombre().equals(" ")){
                    
                JOptionPane.showMessageDialog(this, "CLIENTE ENCONTRADO");
                jBborrar.setEnabled(true);
                jTEncontradonombre.setText(Directorio.buscarCliente(jTFbuscarPor.getText()).getNombre());
                jTencontradoApellido.setText(Directorio.buscarCliente(jTFbuscarPor.getText()).getApellido());
                jTencontradoDni.setText(Directorio.buscarCliente(jTFbuscarPor.getText()).getDni());
                jTencontradoDireccion.setText(Directorio.buscarCliente(jTFbuscarPor.getText()).getDireccion());
                
                
                 }else{
                JOptionPane.showMessageDialog(this, "SIN CLIENTES CON ESE NUMERO");
                }
                
                break;
                
                
                
                
            case 1:
                //buscartelefono() devuelve un arraylist de String
                
                listaClientes.removeAllElements();
                if(jTFbuscarPor.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "SIN APELLIDO PARA BUSCAR");
                }
                
                if(!Directorio.buscarTelefono(jTFbuscarPor.getText()).isEmpty()){
                    
                    jBborrar.setEnabled(true);
                    jTEncontradonombre.setText("");
                    
                    for (Iterator iterator = Directorio.buscarTelefono(jTFbuscarPor.getText()).iterator(); iterator.hasNext();) {
                        Object next = iterator.next();
                        
                        listaClientes.addElement(next);
                    }
                }else {
                    JOptionPane.showMessageDialog(this, "SIN CLIENTES CON ESE APELLIDO");
                }
                
                break;
                
                
                
            case 2:
                
                listaClientes.removeAllElements();
                if(jTFbuscarPor.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "SIN CIUDAD PARA BUSCAR");
                }
                
                if(!Directorio.buscarClientes(jTFbuscarPor.getText()).isEmpty()){
                    
                    
                    jBborrar.setEnabled(true);
                    jTEncontradonombre.setText("");
                    
                    for (Iterator iterator = Directorio.buscarClientes(jTFbuscarPor.getText()).iterator(); iterator.hasNext();) {
                        Object next = iterator.next();
                        
                        listaClientes.addElement(next);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "SIN CLIENTES EN CIUDAD");
                }    
                break;
            
                
                
        }
        
        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBborrarActionPerformed
        
        
        switch(jComboBox1.getSelectedIndex()){
            case 0:
                
                if(Directorio.borrarCliente(jTFbuscarPor.getText())){
                    JOptionPane.showMessageDialog(this, "CLIENTE BORRADO");
                }
                break;
            case 1: 
                
               if(Directorio.borrarCliente(jList1.getSelectedValue())){
                   JOptionPane.showMessageDialog(this, "CLIENTE BORRADO");
                  
               }
              
                
                break;
            case 2:
                               
                
                if(Directorio.borrarCliente(jList1.getSelectedValue())){
                   JOptionPane.showMessageDialog(this, "CLIENTE BORRADO");
                  
                }
                
                
                
                break;
                
            
                
            
            
            
            
            
            
            
        }
    }//GEN-LAST:event_jBborrarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        switch(jComboBox1.getSelectedIndex()){
            case 0:
                listaClientes.removeAllElements();
                jList1.setVisible(false);
                jTEncontradonombre.setVisible(true);
                jTencontradoApellido.setVisible(true);
                jTencontradoDni.setVisible(true);
                jTencontradoDireccion.setVisible(true);
                jTFbuscarPor.setText("ingrese telefono");
                etiqueta_lista_mostrando.setVisible(false);
                jTEncontradonombre.setText("nombre");
                jTencontradoApellido.setText("Apellido");
                jTencontradoDni.setText("dni");
                
                break;
            case 1:
                listaClientes.removeAllElements();
                jTFbuscarPor.setText("ingrese apellido");
                jList1.setVisible(true);
                jTEncontradonombre.setVisible(false);
                jTencontradoApellido.setVisible(false);
                jTencontradoDni.setVisible(false);
                jTencontradoDireccion.setVisible(false);
                etiqueta_lista_mostrando.setVisible(true);
                etiqueta_lista_mostrando.setText("Numeros Asociados al Cliente");
                break;
            case 2: 
                listaClientes.removeAllElements();
                jTEncontradonombre.setVisible(false);
                jTencontradoApellido.setVisible(false);
                jTencontradoDni.setVisible(false);
                jTencontradoDireccion.setVisible(false);
                jTFbuscarPor.setText("Ingrese ciudad");
                jList1.setVisible(true);
                etiqueta_lista_mostrando.setVisible(true);
                etiqueta_lista_mostrando.setText("Numeros Asociados a Ciudad");
                break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTFbuscarPorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFbuscarPorFocusGained
        jTFbuscarPor.setText("");
    }//GEN-LAST:event_jTFbuscarPorFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiqueta_lista_mostrando;
    private javax.swing.JButton jBborrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTEncontradonombre;
    private javax.swing.JTextField jTFbuscarPor;
    private javax.swing.JTextField jTencontradoApellido;
    private javax.swing.JTextField jTencontradoDireccion;
    private javax.swing.JTextField jTencontradoDni;
    // End of variables declaration//GEN-END:variables
}
